"""Idempotently ensure GND pours + antenna/edge keepout rule areas exist (usage: add_zones.py <board>).

The board is generated by scripts/build_pcb.py (which includes this geometry),
but SES imports from the autorouter do not add zones; run this between the last
route import and the final DRC adjudication. Zones are added only if absent so
the script is safe to re-run.

Pitfall #33: rule areas must NOT forbid pads/footprints — they exist only to
carve copper. Pitfall #25: rule areas get priority 1 so they cut the priority-0
GND pours.
"""
import sys
import pcbnew

MM = 1_000_000
BOARD_W, BOARD_H = 66.0, 75.0

KEEPOUTS = [
    ("AntennaKeepout", 16.0, 25.0, 31.0, 40.5),
    ("EdgeConnectorKeepout", 0.0, 60.5, 8.5, 75.0),
    ("LoadCellEdgeKeepout", 0.0, 5.0, 10.5, 18.5),
]


def rect_zone(board, x1, y1, x2, y2):
    z = pcbnew.ZONE(board)
    lc = pcbnew.SHAPE_LINE_CHAIN()
    for px, py in [(x1, y1), (x2, y1), (x2, y2), (x1, y2)]:
        lc.Append(int(px * MM), int(py * MM))
    lc.SetClosed(True)
    z.AddPolygon(lc)
    return z


def main():
    path = sys.argv[1]
    board = pcbnew.LoadBoard(path)
    zones = list(board.Zones())
    rule_areas = [z for z in zones if z.GetIsRuleArea()]
    pours = [z for z in zones if not z.GetIsRuleArea()]
    print("existing: pours", len(pours), "rule_areas", len(rule_areas))

    gnd = board.FindNet("GND")
    if gnd is None:
        raise SystemExit("GND net missing — do not run on a netless board")

    # Pitfall #25: rule areas must outrank the pours to carve them, even
    # when the zones already exist from an earlier (priority-0) generation.
    bumped = 0
    for z in rule_areas:
        if z.GetAssignedPriority() != 1:
            z.SetAssignedPriority(1)
            bumped += 1
    if bumped:
        print("raised rule-area priority to 1:", bumped)

    if len(rule_areas) < len(KEEPOUTS) * 2:
        for name, x1, y1, x2, y2 in KEEPOUTS:
            for layer in (pcbnew.F_Cu, pcbnew.B_Cu):
                z = rect_zone(board, x1, y1, x2, y2)
                z.SetIsRuleArea(True)
                z.SetDoNotAllowPads(False)
                z.SetDoNotAllowTracks(False)
                z.SetDoNotAllowVias(False)
                z.SetDoNotAllowFootprints(False)
                z.SetDoNotAllowCopperPour(True)
                z.SetAssignedPriority(1)
                z.SetLayer(layer)
                board.Add(z)
        print("added keepout rule areas:", len(KEEPOUTS) * 2)
    else:
        print("keepouts already present")

    if not any(z.GetNetname() == "GND" and not z.GetIsRuleArea() for z in board.Zones()):
        pour = [(0.4, 0.4), (BOARD_W - 0.4, 0.4), (BOARD_W - 0.4, BOARD_H - 0.4), (0.4, BOARD_H - 0.4)]
        for layer in (pcbnew.B_Cu, pcbnew.F_Cu):
            z = pcbnew.ZONE(board)
            lc = pcbnew.SHAPE_LINE_CHAIN()
            for px, py in pour:
                lc.Append(int(px * MM), int(py * MM))
            lc.SetClosed(True)
            z.AddPolygon(lc)
            z.SetNetCode(gnd.GetNetCode())
            z.SetLayer(layer)
            z.SetPadConnection(pcbnew.ZONE_CONNECTION_THERMAL)
            z.SetAssignedPriority(0)
            board.Add(z)
        print("added GND pours F.Cu + B.Cu")
    else:
        print("GND pours already present")

    board.Save(path)
    b2 = pcbnew.LoadBoard(path)
    filled = pcbnew.ZONE_FILLER(b2)
    filled.Fill(b2.Zones())
    b2.Save(path)
    b3 = pcbnew.LoadBoard(path)
    for z in b3.Zones():
        if z.GetIsRuleArea():
            continue
        print("filled", z.GetLayerName(), z.GetNetname(), f"{z.GetFilledArea()/1e12:.1f} mm2")


if __name__ == "__main__":
    main()
